Default: &defaults
  database: RedditFollow.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: RedditFollow_test.sqlite3
  <<: *defaults

Staging:
  database: RedditFollow_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: RedditFollow_production.sqlite3
  poolsize: 100
  <<: *defaults
